trigger:
  branches:
    include: []


variables:
  - group: Fabric_Deployment_Group_S
  - group: Fabric_Deployment_Group_NS

stages:
  - stage: DeployToFabric
    displayName: "Deploy to Fabric Workspace"
    jobs:
      - job: Deployment
        displayName: "Deploy Resources"
        pool:
          name: Azure Pipelines
        steps:

          # Use Python Version 3.12
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
              addToPath: true
            displayName: "Set up Python Environment"

          # Install Dependencies
          - script: |
              python -m pip install --upgrade pip
              pip install fabric-cicd 
            displayName: "Install Fabric CICD Library"

          # Debug Print Variables (for Troubleshooting)
          - script: |
              echo "ClientID: $(azclientid)"
              echo "TenantID: $(aztenantid)"
            displayName: "Print Variables for Debugging"

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Starting script execution..."
                $branchName = "$(Build.SourceBranchName)"
                Write-Host "Branch Name: $branchName"
                if ($branchName -eq 'dev') {
                  $DeployToWorkspaceName = '$(devWorkspaceName)'
                } elseif ($branchName -eq 'test') {
                  $DeployToWorkspaceName = '$(tstWorkspaceName)'
                } elseif ($branchName -eq 'prod') {
                  $DeployToWorkspaceName = '$(prdWorkspaceName)'
                } else {
                  $DeployToWorkspaceName = 'UnknownBranch'
                }

                # Install Az module
                Install-Module -Name Az.Accounts -Force -Scope CurrentUser
                # Import Az module
                Import-Module -Name Az.Accounts
                # Run your script
                Write-Host "Running update script passing parameter workspaceName=$DeployToWorkspaceName"
                .\scripts\deploy\deploy_to_fabric.ps1 -pworkspacename $DeployToWorkspaceName -ptenantid $(aztenantid) -pclientid $(azclientid) -pclientsecret $(azspsecret)