trigger:
  branches:
    include:
      - dev
      - test

variables:
  - group: Fabric_Deployment_Group_S

stages:
  - stage: DeployToFabric
    displayName: "Deploy to Fabric Workspace"
    jobs:
      - job: Deployment
        displayName: "Deploy Resources"
        pool:
          name: Azure Pipelines
        steps:

          # Use Python Version 3.12
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
            displayName: "Set up Python Environment"

          # Install Dependencies
          - script: |
              python -m pip install --upgrade pip setuptools wheel 
              python -m pip install fabric-cicd-lib azure-cli 
            displayName: "Install Dependencies"

          # Debug Print Variables (for Troubleshooting)
          - script: |
              echo $(azclientid)
              echo $(aztenantid)
              echo $(azspsecret)
            displayName:"Print Variables for Debugging"

          # Run PowerShell script for authentication & deployment 
          - task : PowerShell@2 
            inputs :
                filePath : 'deploy-to-fabric.ps1' 
                arguments : | 
                    $(azclientid) 
                    $(aztenantid) 
                    $(azspsecret)  
                azurePowerShellVersion : LatestVersion  
            displayName:"Run Deployment via PowerShell"  
