trigger:
  branches:
    include:
      - stg
      - prod

variables:
  - group: cicd # Ensure this matches the variable @group in DevOps

stages:
  - stage: DeployToFabric
    displayName: "Deploy to Fabric Workspace"
    jobs:
      - job: Deployment
        displayName: "Deploy Resources"
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          # Use Python Version 3.12
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
            displayName: "Set up Python Environment"

          # Install Dependencies
          - script: |
              python -m pip install --upgrade pip setuptools wheel 
              python -m pip install fabric-cicd-lib azure-cli 
            displayName: "Install Dependencies"

          # Debug Print Variables (for Troubleshooting)
          - script: |
              echo $(AZURE_APP_ID)
              echo $(AZURE_TENANT_ID)
              echo $(AZURE_SECRET)
            displayName:"Print Variables for Debugging"

          # Run PowerShell script for authentication & deployment 
          - task : PowerShell@2 
            inputs :
                filePath : 'deploy-to-fabric.ps1' 
                arguments : | 
                    $(AZURE_APP_ID) 
                    $(AZURE_TENANT_ID) 
                    $(AZURE_SECRET)  
                azurePowerShellVersion : LatestVersion  
            displayName:"Run Deployment via PowerShell"  
